
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace School
{

using System;
    using System.Collections.Generic;
    
public partial class Schedule
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Schedule()
    {

        this.VisitLeson = new HashSet<VisitLeson>();

    }


    public int id { get; set; }

    public int IdLessonEmployee { get; set; }

    public int NumberCabinet { get; set; }

    public System.DateTime DataTimeStart { get; set; }

    public System.DateTime DataTimeFinich { get; set; }



    public virtual Cabinet Cabinet { get; set; }

    public virtual LessonEmployee LessonEmployee { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VisitLeson> VisitLeson { get; set; }

}

}
