//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id { get; set; }
        public int NumberCabinet { get; set; }
        public int idLessonEmployee { get; set; }
        public Nullable<System.DateTime> DataTimeStart { get; set; }
        public Nullable<System.DateTime> DataTimeFinich { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual LessonEmployee LessonEmployee { get; set; }
    }
}
