

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace School
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class School1Entities : DbContext
{
    public School1Entities()
        : base("name=School1Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cabinet> Cabinet { get; set; }

    public virtual DbSet<Class> Class { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<JobTitle> JobTitle { get; set; }

    public virtual DbSet<Lesson> Lesson { get; set; }

    public virtual DbSet<LessonEmployee> LessonEmployee { get; set; }

    public virtual DbSet<Schedule> Schedule { get; set; }

    public virtual DbSet<Student> Student { get; set; }

    public virtual DbSet<TypeCabinet> TypeCabinet { get; set; }

    public virtual DbSet<VisitLeson> VisitLeson { get; set; }

}

}

