
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace School
{

using System;
    using System.Collections.Generic;
    
public partial class VisitLeson
{

    public int id { get; set; }

    public int IdSchedule { get; set; }

    public int IdStudent { get; set; }



    public virtual Schedule Schedule { get; set; }

    public virtual Student Student { get; set; }

}

}
